--- #YAML:1.0
name:                HeliosX-ExtLoggerService
version:             0.02_0771
abstract:            Helios::Service class to allow Helios logging to external logging systems
license:             perl
author:              
    - Andrew Johnson <lajandy at cpan dotorg>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Helios:                        2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
